
# Available commands: https://nikitabobko.github.io/AeroSpace/commands

after-login-command = ['exec-and-forget sketchybar',
'exec-and-forget borders active_color=0xff494d64 inactive_color= 0xffe1e3e4 width=5.0']

after-startup-command = ['exec-and-forget sketchybar',
'exec-and-forget borders active_color=0xff494d64 inactive_color= 0xffe1e3e4 width=5.0']

exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

key-mapping.preset = 'qwerty'

accordion-padding = 30

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       0
outer.bottom =     0
outer.top =        0
outer.right =      10   

[mode.main.binding]

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-shift-f = 'fullscreen'
alt-shift-m = 'macos-native-minimize'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-semicolon = 'mode service'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'

[workspace-to-monitor-force-assignment]

1 = 'main'

2 = 'main'

3 = 'main'

4 = 'main'

5 = ['secondary', 'main']


[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] 
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

[[on-window-detected]]
if.app-id='company.thebrowser.Browser'
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id='com.apple.Safari'
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id='com.googlecode.iterm2'
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id='com.microsoft.VSCode'
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id='com.apple.Terminal'
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id='com.jetbrains.pycharm'
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id='com.colliderli.iina'
run = "move-node-to-workspace 3"

[[on-window-detected]]
if.app-id='notion.id'
run = "move-node-to-workspace 4"

[[on-window-detected]]
if.app-id='com.apple.Notes'
run = "move-node-to-workspace 4"

[[on-window-detected]]
if.app-id='com.microsoft.Word'
run = "move-node-to-workspace 4"

[[on-window-detected]]
if.app-id='com.apple.iWork.Pages'
run = "move-node-to-workspace 4"

[[on-window-detected]]
if.app-id='com.microsoft.Powerpoint'
run = "move-node-to-workspace 4"

[[on-window-detected]]
if.app-id='net.whatsapp.WhatsApp'
run = "move-node-to-workspace 5"

[[on-window-detected]]
if.app-id='ru.keepcoder.Telegram'
run = "move-node-to-workspace 5"

[[on-window-detected]]
if.app-id='com.readdle.smartemail-Mac'
run = "move-node-to-workspace 5"

