version = 3
final_space = true

[palette]
  blush = '#DA627D'
  plum = '#9A348E'
  salmon = '#FCA17D'
  sky = '#86BBD8'
  tan = '#CC3802'
  teal = '#047E84'
  teal_blue = '#33658A'
  white = '#FFFFFF'
  black = '#000000'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'rprompt'
  alignment = 'left'

  [[blocks.segments]]
    leading_diamond = ''
    template = '{{ if .Env.PNPPSHOST }}  {{ .Env.PNPPSHOST }} {{ end }}'
    foreground = 'p:white'
    background = 'p:tan'
    type = 'text'
    style = 'diamond'

  [[blocks.segments]]
    template = '{{ if .Env.PNPPSSITE }}  {{ .Env.PNPPSSITE }}{{ end }}'
    foreground = 'p:white'
    powerline_symbol = ''
    background = 'p:teal'
    type = 'text'
    style = 'powerline'

  [[blocks.segments]]
    trailing_diamond = ''
    template = '{{ if .Env.PNPPSSITE }} {{ end }}'
    foreground = 'p:white'
    background = 'p:teal'
    type = 'text'
    style = 'diamond'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    leading_diamond = ''
    template = "\uf179 {{ .UserName }} "
    foreground = 'p:white'
    background = 'p:plum'
    type = 'session'
    style = 'diamond'

  [[blocks.segments]]
    template = '  {{ .Path }} '
    foreground = 'p:white'
    powerline_symbol = ''
    background = 'p:blush'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    template = '​'
    foreground = 'p:sky'
    background = 'p:sky'
    type = 'text'
    style = 'powerline'
    powerline_symbol = ''

   [[blocks.segments]]
    template = '​'
    foreground = 'p:teal_blue'
    background = 'p:teal_blue'
    type = 'text'
    style = 'powerline'
    powerline_symbol = ''

   [[blocks.segments]]
    template = '​'
    foreground = 'p:teal'
    background = 'p:teal'
    type = 'text'
    style = 'powerline'
    powerline_symbol = ''

  [[blocks.segments]]
  type = "git"
  style = "powerline"
  background = "#F7768D"
  foreground = "p:white"
  leading_diamond = "\ue0b6"
  powerline_symbol = "\ue0b0"
  trailing_diamond = "\ue0b4"
  template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }} "
  background_templates = [
    "{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}",
    "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}",
    "{{ if gt .Ahead 0 }}#B388FF{{ end }}",
    "{{ if gt .Behind 0 }}#B388FF{{ end }}"
  ]
  
    [blocks.segments.properties]
    branch_template = "{{ trunc 25 .Branch }}"
    fetch_stash_count = true
    fetch_status = true
    fetch_upstream_icon = true


  # Execution time segment
  [[blocks.segments]]
  type = "executiontime"
  style = "diamond"
  background = "p:teal_blue"
  foreground = "#ffffff"
  trailing_diamond = ''
  template = " \uf252 {{ .FormattedMs }}\u2800"
  background_templates = [
    "{{ if gt .Code 0 }}#c40202{{ end }}"
  ]
  
    [blocks.segments.properties]
    always_enabled = true



#[[blocks.segments]]
#   trailing_diamond = ''
#    template = ' ♥ {{ .CurrentDate | date .Format }} '
#    foreground = 'p:white'
#    background = 'p:teal_blue'
#    type = 'time'
#    style = 'diamond'

# [blocks.segments.properties]
#time_format = '3:04'


[[blocks]]
  alignment = "left"
  newline = true
  type = "prompt"
  
  [[blocks.segments]]
    foreground = 'p:blush'
    style = "plain"
    template = "\u276f"
    type = "status"
    
    [blocks.segments.properties]
      always_enabled = true
    

